spring.application.name=inventory-control

# 1. Ativa perfil dev
spring.profiles.active=dev

# 2. Estratégia de atualização do banco (IMPORTANTE)
# Use "update" para o Hibernate criar/alterar tabelas automaticamente baseado nas suas classes Java
spring.jpa.hibernate.ddl-auto=update

# 3. Para ver o SQL que o Spring gera no console (Ótimo para aprender!)
spring.jpa.show-sql=true
