# 1. A URL de conexão
# O padrão é jdbc:postgresql://localhost:PORTA/NOME_DO_BANCO
spring.datasource.url=jdbc:postgresql://localhost:5433/controle_estoque

# 2. Credenciais
spring.datasource.username=admin
spring.datasource.password=49!ntlbSDL*L

# 3. Driver do PostgreSQL (Opcional nas versões novas, mas bom colocar)
spring.datasource.driver-class-name=org.postgresql.Driver